INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('New Queen Street', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Workshop Island', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Circuit Royal', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Runasapi', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ayutthaya', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Black Forest', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Blizzard World', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Busan', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Castillo', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Chateau Guillard', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Colosseo', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Dorado', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ecopoint Antarctica', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Esperanca', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Havana', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Horizon Lunar Colony', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ilios', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Junkertown', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Kings Row', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Necropolis', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('New Junk City', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Workshop Expanse', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Numbani', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Oasis', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Paraiso', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Petra', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Practice Range', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Rialto', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Samoa', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Shambali', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Suravasa', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Throne Of Anubis', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Volskaya Industries', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Watchpoint Gibraltar', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Workshop Chamber', 'background', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Lijiang Tower', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Eichenwalde', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Midtown', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Hanaoka', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Route 66', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Kanezaka', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Temple Of Anubis', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Malevento', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Hanamura', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Nepal', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Paris', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Hollywood', 'background', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Meditation', 'background', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Red Alert', 'background', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Calm', 'background', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Speed', 'background', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Sparks', 'background', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Cyber', 'background', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Cyberdemon', 'background', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('100', 'coins', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('250', 'coins', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('500', 'coins', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('1000', 'coins', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Medal', 'pose', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Shuriken', 'pose', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Kneeling', 'pose', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Meditate', 'pose', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Over The Shoulder', 'pose', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Sword Stance', 'pose', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Pounce', 'pose', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Cinnabar', 'skin', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Malachite', 'skin', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ochre', 'skin', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Overwatch 2', 'skin', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Carbon Fiber', 'skin', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Junker', 'skin', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Nihon', 'skin', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Nomad', 'skin', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Sparrow', 'skin', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Bedouin', 'skin', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Sentai', 'skin', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Kendoka', 'skin', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Karasutengu', 'skin', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Blackwatch', 'skin', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Bushi', 'skin', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Oni', 'skin', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Street Runner', 'skin', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Baihu', 'skin', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('God Of War', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Icon', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Nin', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Shimada', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Shuriken', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Signature', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Stoic', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Warrior', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Assassin', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Green Ninja', 'spray', 'common', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Prepared', 'spray', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ryugekiken', 'spray', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Stance', 'spray', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Swords', 'spray', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Brickblade', 'spray', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Soul', 'spray', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Dragon Dance', 'spray', 'rare', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Target Practice', 'spray', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Cute', 'spray', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ramen', 'spray', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Pixel', 'spray', 'epic', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Blackwatch', 'spray', 'legendary', 'Classic');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Black Forest Winter', 'background', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Blizzard World Winter', 'background', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ecopoint Antarctica Winter', 'background', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Hanamura Winter', 'background', 'epic', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Kings Row Winter', 'background', 'epic', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Paying Respects', 'pose', 'epic', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Toast', 'pose', 'epic', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Azurite', 'skin', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Young Genji', 'skin', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Chrome', 'skin', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ice Wraith', 'skin', 'legendary', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Jotunn', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Mountain Man', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Polar Bear', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Snow Snow Snow', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Snowcole', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Snowhog', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Snowmei', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Snowreaper', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Winter Wonderland', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ice Spheres', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Dragon Blade', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Kaze No Gotoku', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Lunge', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Holiday Surprise', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Frozen Throne', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Cookie Throw', 'spray', 'common', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Mutual Thaw', 'spray', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Bonk', 'spray', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Frozen Elf', 'spray', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Yeti Hunter', 'spray', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Yeti Rage', 'spray', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Ice Wraith', 'spray', 'rare', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Divine Monkey', 'spray', 'epic', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Yeti', 'spray', 'epic', 'Winter');
INSERT INTO lootbox.reward_types (name, type, rarity, key_type) VALUES ('Demonic Deflection', 'spray', 'legendary', 'Winter');
