name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_HOST_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST_IP }} >> ~/.ssh/known_hosts

      - name: Set up Docker context for prod
        run: |
          docker context create prod-server \
            --docker "host=ssh://${{ secrets.SERVER_HOST_USER }}@${{ secrets.SERVER_HOST_IP }}" \
            --description "Prod server context"
          docker context use prod-server

      - name: Deploy to Remote Prod Server
        run: |
          echo "Deploying to Prod Server..."

          docker compose -f docker-compose.yml up -d --build --no-deps --force-recreate

        env:
          API_ENVIRONMENT: ${{ secrets.API_ENVIRONMENT }}
          DEFAULT_DSN: ${{ secrets.DEFAULT_DSN }}
          RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASS: ${{ secrets.RABBITMQ_PASS }}
          RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          LUST_URL: ${{ secrets.LUST_URL }}
          IP_HASH_SECRET: ${{ secrets.IP_HASH_SECRET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
